### ISSUE TITLE
Margins outside of browser window

### ISSUE THREAD

**Issue by apennebaker** [42sixsolutions/deckster#10]
Deckster isn't respecting my browser window size. Even when I maximize my window on an external monitor, tiles still stick outside the window.

Screenshot:

![too-big](https://f.cloud.github.com/assets/5123438/926735/ac603656-ff91-11e2-91fc-cf24eacac696.png)

**Comment by bscazzero42six** [comment]
yeah. we should probably adjust the deck so its equal to the window size. I'll run this by the product guys to make sure its what they want.

**Comment by apennebaker** [comment]
Decks should be configurable for any size, but default to no more than the window size.

**Comment by ghochard42six** [comment]
I don't know if that's true.  At the very least, the UI developer should be able to specify card height/width and deck vertical/horizontal gutters in pixels.  In that case, you would have a horizontal scroll if your window is too small.  Though I agree that horizontal scrolls usually suck.  Supporting % would be very interesting.  Also, the UI developer should be able to do media queries on the screen size and adjust from there.  Derek has done this in one of our projects.
