### ISSUE TITLE
Can't drag tiles around

### ISSUE THREAD

**Issue by apennebaker** [42sixsolutions/deckster#11]
On my machine, when I release a tile, it stays in the same position.

Blocking https://fourtwosix.jira.com/browse/OR-55.

**Comment by bscazzero42six** [comment]
Try updating again. I submitted another iteration. What browser and version # are you using?

**Comment by apennebaker** [comment]
```
Google Chrome   28.0.1500.95 (Official Build 213514) 
OS  Mac OS X 
Blink   537.36 (@154530)
JavaScript  V8 3.18.5.14
Flash   11.8.800.97
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36
Command Line     /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_37512132 --flag-switches-begin --enable-sync-favicons --sync-keystore-encryption --flag-switches-end
Executable Path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path    /Users/apennebaker/Library/Application Support/Google/Chrome/Default
Variations  853359fa-f7de5af1
6dcb530d-91bf853e
b03ddc1f-75e383c2
f9b252d0-fd526c81
c7d93845-edcb5ee0
24dca50e-837c4893
ca65a9fe-91ac3782
f75c0e23-4ad60575
5a3c10b5-e1cc0f14
244ca1ac-4ad60575
f47ae82a-746c2ad4
5e29d81-cf4f6ead
246fb659-7564fb06
f296190c-cdc3d902
4442aae2-7158671e
75f0f0a0-4ad60575
e2b18481-e1cc0f14
e7e71889-e1cc0f14
```

**Comment by apennebaker** [comment]
I can't drag tiles around in Chrome. See https://github.com/42sixsolutions/deckster/issues/13.

**Comment by bscazzero42six** [comment]
Are you only experiencing this issue in chrome? It might be related to an individual setting you have. Its working fine for me in chrome. Rob, Myong is your drag and drop working in chrome?

**Comment by mchong** [comment]
It's working in Chrome for me. Andrew - I see in your screenshot in issue
#13 that the URL of demo.html is opened directly from the file system. Ben
recommended to me to run the project in a local web server instead of
directly from the file system - that should fix the issue.

**Comment by rschmertz** [comment]
Yep, there's a difference depending on whether you open it as a local file or over http.  As a file, the document.stylesheets[0].cssRules doesn't get populated, and our code throws an exception.

**Comment by bscazzero42six** [comment]
Our project should always be access from a web server.

**Comment by apennebaker** [comment]
Dup of #13.
