### ISSUE TITLE
Move/Close buttons now missing

### ISSUE THREAD

**Issue by apennebaker** [42sixsolutions/deckster#13]
Screenshot:

![screen shot 2013-08-08 at 1 16 42 pm](https://f.cloud.github.com/assets/5123438/933058/613ec026-004e-11e3-8da1-a28b61e66770.png)

**Comment by bscazzero42six** [comment]
Is this still an issue? The current source code on github doesn't have this problem.

**Comment by apennebaker** [comment]
Yes, this behavior still occurs in Chrome.

**Comment by mchong** [comment]
I see in your screenshot that the URL of demo.html is opened directly from the file system.  Ben recommended to me to run the project in a local web server instead of directly from the file system - that should fix the issue.

**Comment by apennebaker** [comment]
@mchong @bscazzero42six Thanks for the tip!

https://github.com/42sixsolutions/deckster/commit/9436edada026c2373201766b83c943f699c2c1e0
