### ISSUE TITLE
Firefox: Dragging tiles often results in all the other tiles being hidden offscreen

### ISSUE THREAD

**Issue by apennebaker** [42sixsolutions/deckster#14]
Sometimes dragging tiles works, but 50% of the time, this results in all the other tiles being hidden offscreen.

Using Firefox 22.0 on Mac OS X 10.8.4.

**Comment by bscazzero42six** [comment]
I believe I was experiencing a similar issue. I just added new code that will hopefully fix that issue. Can you update and let me know if you're having the same issue?

**Comment by bscazzero42six** [comment]
Also I'm assuming you're now able to drag and drop tiles around?

**Comment by apennebaker** [comment]
Much better!
