### ISSUE TITLE
Styling from child page can affect all of Deckster

### ISSUE THREAD

**Issue by rschmertz** [42sixsolutions/deckster#16]
I've modified sample3.html to demonstrate the issue.  Interesting problem!

**Comment by bscazzero42six** [comment]
I see the issue. We can discuss this as a team later on but I think its the responsibility of the developer to make sure he/she isn't loading malicious code.

**Comment by ghochard42six** [comment]
Agree.  Also, deckster shouldn't change the style and look of content outside of the deckster deck, such as a CSS reset.
