### ISSUE TITLE
Showing as paragraph layout

### ISSUE THREAD

**Issue by apennebaker** [42sixsolutions/deckster#17]
Latest revision is showing in paragraph form, in Firefox and Chrome.

Screenshot:

![screen shot 2013-08-09 at 2 41 44 pm](https://f.cloud.github.com/assets/5123438/940069/7b454924-0123-11e3-8973-dd066478c90f.png)

**Comment by bscazzero42six** [comment]
The location of the scss file was changed. make sure your refresh/update demo.html page.

**Comment by bscazzero42six** [comment]
What I mean is make sure your compiled scss file gets placed into the new directory (/public/stylesheets/)

**Comment by rschmertz** [comment]
I've updated the Makefile, so running make should fix this.

**Comment by apennebaker** [comment]
@rschmertz git head still results in paragraph form when I `make serve`.

**Comment by rschmertz** [comment]
Fixed Makefile some more :-)

**Comment by apennebaker** [comment]
@rschmertz That fixed it!
