### ISSUE TITLE
Placement of "Removed Cards" menu

### ISSUE THREAD

**Issue by rschmertz** [42sixsolutions/deckster#20]
Since I'm playing with two decks (this in addition to not playing with a full deck ;-), it looks a little weird to have the Removed Cards menu fixed in the corner of the page, scrolling up with the whole page, while the scroll-helper buttons stay in the page.  I wonder if the Removed Cards button should be attached to each deck.  Decks now get wrapped in a container generated by JS to contain a title div; perhaps this could be leveraged.

**Comment by mchong** [comment]
Fixed - moved 'Removed Cards' dropdown menu to above each deck's title on the left.

**Comment by mchong** [comment]
Looking into issue when there are two 'Removed Cards' dropdown menu - they doesn't behave correctly.

**Comment by mchong** [comment]
Fixed
