### ISSUE TITLE
Deck Title should be optional

### ISSUE THREAD

**Issue by ghochard42six** [42sixsolutions/deckster#22]
If "data-title" is not define in a deck, the default html value should be empty

**Comment by bscazzero42six** [comment]
Done. No HTML title elements will appear if data-title is not defined on the deck.

**Comment by bscazzero42six** [comment]
Actually, what would you like the "Jump To Deck" functionality to show for decks w/ no title?

**Comment by ghochard42six** [comment]
I guess the ID of the deck or just "Deck 1", "Deck 2"

On Mon, Aug 26, 2013 at 12:19 PM, bscazzero42six
notifications@github.comwrote:

> Actually, what would you like the "Jump To Deck" functionality to show for
> decks w/ no title?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/42sixsolutions/deckster/issues/22#issuecomment-23275174
> .

## 

_Greg Hochard_
Lead Developer, 42six Solutions

(m) 410-507-2427
ghochard@42six.com

_"Deliver."_
*
*

**Comment by ghochard42six** [comment]
Looks good
