### ISSUE TITLE
Deck controls should be with the title

### ISSUE THREAD

**Issue by ghochard42six** [42sixsolutions/deckster#23]
The deck controls, such as jump to, should be within the same parent element as the deck title.

**Comment by rschmertz** [comment]
The current implementation is designed so that the "jump to" functionality is always accessible.  If I want to jump to a given deck, would each deck titlebar have the dropdown menu with the list of all the decks?

**Comment by ghochard42six** [comment]
After discussing with Ben, we've decided the keep the jump-deck where it's at currently.  But the Jump Card should be moved to the deck-title.
