### ISSUE TITLE
Preexisting widget frameworks

### ISSUE THREAD

**Issue by apennebaker** [42sixsolutions/deckster#4]
A handful of clean, reusable widget frameworks are graciously provided by the community. Maybe we could drop these into our projects and save a few weeks of effort?
# Free and Open Source

The following libraries have a permissive MIT-style license, allowing for use in any environment, including nonGPL environments.
- [jQuery Gridly](http://ksylvest.github.io/jquery-gridly/) - A good, simple demo of draggable, closable grid elements.
- [sDashboard](https://github.com/ModelN/sDashboard) - A colorful demo of draggable, closable, and expandable grid elements. Includes a separate, live [demo](http://modeln.github.io/sDashboard/example/ex.html).
- [jQuery Draggable Widget](http://api.jqueryui.com/draggable/) - A popular jQuery-based framework for web widgets, with simple settings for grid layouts. Includes several options for a fully custom user experience.
- [Ozone](https://www.owfgoss.org/) - The domain standard for web widgets. Does 80% of what we want by default.
# Commercial

Packery is available by GPL for noncommercial projects, and available for commercial projects with a very small, one time purchase.
- [Packery](http://packery.metafizzy.co/) even uses a binpacking algorithm to avoid ugly gaps, while still allowing designers to customize grid layouts.

**Comment by ghochard42six** [comment]
We did try looking into other frameworks.  Of course there's always more to look into.  Some did a decent percentage of the features, Gridster for example.  But modifying these to get the rest of the features became troublesome.  This is an attempt to create something that does exactly what we want, and to make it easy to customize and add features for future use.  This may be a miss, but we wanted to take a shot at it.
